### ISSUE TITLE
`log.SetFlags(0)` doesn't remove timestamp from log lines, preventing `InferLevels` to work properly

### ISSUE THREAD

**Issue by lgfa29** [hashicorp/go-hclog#100]
While working on https://github.com/hashicorp/nomad/pull/11291 I wasn't able to get `InferLevels` to work properly because the log lines generated by external dependencies still had the timestamp.

Maybe we can extend the [search scope ](https://github.com/hashicorp/go-hclog/blob/master/stdlog.go#L60-L71)from `HasPrefix` to `Contains`?

**Comment by evanphx** [comment]
I don't really want to expand the scope to `Contains` because it's too easy to get a false positive. Can nomad turn timestamps off on it's logger instead?

**Comment by lgfa29** [comment]
Yeah, makes sense. I tried to disable the timestamps from Nomad [here](https://github.com/hashicorp/nomad/blob/v1.2.0-beta1/command/agent/command.go#L669), but these log lines are coming from external dependencies (like [mdns](https://github.com/hashicorp/mdns/blob/master/client.go#L120) for example). Even calling `log.SetFlags` in an `init` function in the `main` package didn't help.

What do you think about making the search scope configurable? So callers would be able to do something like:

```go
&hclog.StandardLoggerOptions{
    InferLevels: true,
    InferLevelFullLine: true,
})
```

But with a better name 😅
