### ISSUE TITLE
UTC timezone

### ISSUE THREAD

**Issue by binaek** [hashicorp/go-hclog#103]
Is there any option to log with `UTC` instead of the location time zone?

I found a `time.Now()` in https://github.com/hashicorp/go-hclog/blob/master/intlogger.go#L155, but couldn't find anything else

**Comment by evanphx** [comment]
There isn't. If you set the TZ env var to UTC when the program starts, then `time.Now()` should return UTC timestamps.

**Comment by binaek** [comment]
@evanphx Thanks for your quick response. Unfortunately, relying on the `TZ` env var being set does not work for me.

I raised a PR at https://github.com/hashicorp/go-hclog/pull/104

Can somebody take a look whether it can be merged in?
