### ISSUE TITLE
Syntax error in an example in the README.md

### ISSUE THREAD

**Issue by siddharthborderwala** [hashicorp/go-hclog#105]
I would like to point out that there is a small syntax error in an example in the readme of the project, minor correction required.

[![image](https://user-images.githubusercontent.com/54456279/146724902-84f964f5-72ee-4451-9323-787f2a6001ae.png)](https://github.com/hashicorp/go-hclog#using-hclogfmt)

Corrected version -

```go
var totalBandwidth int = 200
```

**Comment by evanphx** [comment]
Thank you! Fixed that.
