### ISSUE TITLE
consider removing the empty colon (`:`) when message is empty

### ISSUE THREAD

**Issue by marco-m** [hashicorp/go-hclog#109]
Hello,

consider the case when you don't really have a message, just a list of k/v pairs:
```go
log.Debug("", "dbVersion", dbVersion)
```
this will print
```
2022-04-12T21:24:54+0200 [DEBUG] myprog: : dbVersion=0
```
I would like instead to see simply:
```
2022-04-12T21:24:54+0200 [DEBUG] myprog: dbVersion=0
```

What do you think?

**Comment by marco-m** [comment]
hello @evanphx, I am confused.

I realized that commit 78f517c is actually on branch `f-no-colon`, which is unmerged, while this issue is closed.
Since the issue is closed and there is no associated PR, is the `f-no-colon` branch risking to be forgotten? 

Thanks :-)

**Comment by evanphx** [comment]
That was weird of me. I'll get that moved over now.

**Comment by marco-m** [comment]
Thanks!
