### ISSUE TITLE
No way to remove "timestamp=xxx" when logging from a go-plugin

### ISSUE THREAD

**Issue by spatel95** [hashicorp/go-hclog#129]
I am trying to capture logs from a plugin and keep getting `2023-05-17T13:46:44.006-0400 [WARN]  some.module: some log message: timestamp=2023-05-17T13:46:44.006-0400`. 

When I set  `DisableTime: true` in `hclog.LoggerOptions` 
I get `2023-05-17T13:46:44.006-0400 [WARN]  some.module: some log message:  timestamp=0001-01-01T00:00:00.000Z`

Is there a way around this? It makes reading the logs quiet messy

**Comment by evanphx** [comment]
The field is being added by your code and/or the plugin. If you're not seeing it where you perform a call to `.Warn`, then somewhere else there is code doing `.With("timestamp", time.Now())` to create a logger that has the timestamp as a default field.

**Comment by evanphx** [comment]
Looks like it comes from here: https://github.com/hashicorp/go-plugin/blob/e889c1ba1044d1b183d4ed45d0f2f531db3ba50b/client.go#L1051

**Comment by spatel95** [comment]
@evanphx 
Hmm, looks like that's it. I don't think I can change it without a PR to go-plugin. Thank you, Evan!
