### ISSUE TITLE
Provide implementation to `logr`

### ISSUE THREAD

**Issue by acabarbaye** [hashicorp/go-hclog#130]
[`logr`](https://github.com/go-logr/logr) provides a generic interface for loggers in go and is being used in a lot of places now e.g. kubernetes, etc.
Would it be possible to provide an [implementation](https://github.com/go-logr/logr#implementations-non-exhaustive) using `hclog`?

There seems to have been an attempt to do so but the project has not been updated for a while https://github.com/alauda/logr-hclog

**Comment by evanphx** [comment]
Hi @acabarbaye, I went ahead and wrote it up for ya!

https://github.com/evanphx/hclogr
