### ISSUE TITLE
Detect common interfaces in JSONFormat values 

### ISSUE THREAD

**Issue by jbardin** [hashicorp/go-hclog#14]
Plugin errors weren't being printed in terraform, because the error values are being dropped directly into the logger arguments. Since `error.errorString` has no exported fields, when `JSONFormat` is used it's marshaled as an empty object.

Should hclog detect `error` and Stringer` and marshal them as strings instead?

**Comment by evanphx** [comment]
A good idea. I’ll write it up.

**Comment by jbardin** [comment]
I had an old checkout, -- this was added in #9. 

Handling `Stringer` may not be a as good an idea, because it's often implemented on rich structs which one may expect to be marshaled correctly into json.
