### ISSUE TITLE
Please provider a option to determine whether do escape or not when log in json format

### ISSUE THREAD

**Issue by Ericwww** [hashicorp/go-hclog#140]
Currently, when `intLogger` log in json format. It will call `json.NewEncoder` and do Encode.

But, the `escapeHTML` in `json.Encoder` is default to true. So when I want to log some info which will refer these symbol: &, <, and >, the log result is unexpected.

I would like to submit a PR to enhance it.

**Comment by Ericwww** [comment]
@evanphx 
Is there will be a new version release for this issue or PR?

**Comment by evanphx** [comment]
@Ericwww Thanks for the reminder, push published 1.6.3 with it.
