### ISSUE TITLE
json logger panics on write failures

### ISSUE THREAD

**Issue by notnoop** [hashicorp/go-hclog#38]
The json logger unexpectedly panics when writing json format to writer backend fails: https://github.com/hashicorp/go-hclog/blob/6907afbebd2eef854f0be9194eb79b0ba75d7b29/intlogger.go#L370-L373.  In contrast the plain text formatter ignores any write error: https://github.com/hashicorp/go-hclog/blob/6907afbebd2eef854f0be9194eb79b0ba75d7b29/intlogger.go#L145-L256 .

We noticed it because json logger paniced when writing to Stderr, a closed pipe at the time.  You can find more details in https://github.com/hashicorp/go-plugin/issues/114 .

I'd suggest treating logging here as best-effort (like in the non-json case), or returning and propagating the error back to make it an application concern.

Also, I may suggest distinguishing between write failures (ignore these) and json marshaling failures (in which case, add a log line indicating a log line was dropped due to json incompatibility).

I'd be happy to submit a PR with the suggested changes if they seem reasonable to maintainers.

**Comment by evanphx** [comment]
Yes, the code should be removed such that if Encode() fails we move on silently. Go ahead and submit that PR.
