### ISSUE TITLE
Support Color-coded log lines

### ISSUE THREAD

**Issue by RobbieMcKinstry** [hashicorp/go-hclog#41]
Hello fellow HashiCorporeals!

Have we discussed color-coding log levels? In the research team, we wrapped hc-log to colorize INFO as blue, WARN as RED, etc. I imagine Mitchell's [colorstring library](https://github.com/mitchellh/colorstring) would probably do the trick.

Is there a world in which this becomes a possible, opt-in feature of hc-log?

**Comment by evanphx** [comment]
An opt-in feature that doesn't effect performance when disabled is fine.
