### ISSUE TITLE
Wrapper to create a hclog from a stdlib logger

### ISSUE THREAD

**Issue by F21** [hashicorp/go-hclog#45]
This is sort of a redux of https://github.com/hashicorp/go-hclog/issues/11

Recently, https://github.com/hashicorp/raft switched to using hclog (https://github.com/hashicorp/raft/pull/321), which broke our client code as we use https://github.com/uber-go/zap for logging.

The original author of https://github.com/hashicorp/go-hclog/issues/11 was able to solve his problem, but I don't think it's possible to use the same approach with zap.

It would be nice if go-hclog has a function that can wrap around a stdlib logger (zap can derive a stdlib logger), which can then be used with other loggers. This is useful for projects that has standardized on a logger other than hclog and do not wan to introduce a new logger to the stack.

A temporary workaround is to be write a wrapper for each project, but I think this is something that's generalized enough, so it should be possible to implement a function to turn a stdlib logger into a hclog.

**Comment by F21** [comment]
For zap, here's a hcl log wrapper: https://github.com/serverless/event-gateway/blob/92b773f27dc856fa3db08c772963cb8c64f1ce89/plugin/logger.go

It's missing the `StandardWriter(opts *StandardLoggerOptions) io.Writer`, method, but otherwise it's pretty complete.

**Comment by RobbieMcKinstry** [comment]
Hi @F21 , thanks for opening this issue.

Just for my own clarification, you're looking for a package-level function with a signature like this:

```go
import "log"

func WrapStd(*log.Logger) hclog.Logger {}
```
more or less doing the inverse of the `hclog.Logger.StandardLogger` function. Is that correct?

**Comment by F21** [comment]
@RobbieMcKinstry Yes! 👍
