### ISSUE TITLE
Make InterceptLogger conform to the OutputResettable interface

### ISSUE THREAD

**Issue by raskchanky** [hashicorp/go-hclog#61]
Hello!  👋 

I'm currently in the process of implementing a `monitor` command for Vault, similar to the Nomad and Consul commands of the same name.  I'm using `InterceptLogger` but there are a few places where it needs to be `OutputResettable`.  Does that feel like something appropriate to add?  If so, I'm happy to author a PR that makes those changes.  If not, I'd appreciate any suggestions y'all might have.

**Comment by evanphx** [comment]
A PR for that is fine. It's an oversight that it doesn't conform already.
