### ISSUE TITLE
Last commit is making go-plugin to break

### ISSUE THREAD

**Issue by viejodecaldas** [hashicorp/go-hclog#85]
Hi there,

Today I found that my libraries were breaking because of `undefined: hclog.TimeFormat` error.
Did some quick investigation and found that this const name changed and is making `hashicorp/go-plugin` to break.
Would you mind taking a look at this?

Cheers

**Comment by evanphx** [comment]
Oh sure, sorry about that!

**Comment by evanphx** [comment]
#86 has fixed this, sorry about that!

**Comment by viejodecaldas** [comment]
Thank you very much! =D
