### ISSUE TITLE
String values should have `"` escaped

### ISSUE THREAD

**Issue by banks** [hashicorp/go-hclog#98]
See https://play.golang.org/p/BLpvFfNxGIR

Expected output:
```
2009-11-10T23:00:00.000Z [ERROR] An error occurred!: msg="\"foo\" is not a valid name"
```
This format isn't formally described anywhere but it currently doesn't allow unambiguous parsing. Using `\` as an escape char seems to be common enough that many existing parsers will have a way to do that.

Actual output:
```
2009-11-10T23:00:00.000Z [ERROR] An error occurred!: msg=""foo" is not a valid name"
```

**Comment by schmichael** [comment]
FWIW you can force a field to always be quoted with [`hclog.Quote(msg)`](https://pkg.go.dev/github.com/hashicorp/go-hclog#Quote)

https://play.golang.org/p/AzjEvA8wqGy

Although now I wonder if I added it in #96  because I didn't realize the behavior in this issue is a bug!
